add_custom_target(examples)

add_subdirectory(examples/workflow_api/basic-examples/bare-metal-chain)
add_subdirectory(examples/workflow_api/basic-examples/bare-metal-chain-scratch)
add_subdirectory(examples/workflow_api/basic-examples/bare-metal-bag-of-tasks-programmatic-platform)
add_subdirectory(examples/workflow_api/basic-examples/bare-metal-multicore-tasks)
add_subdirectory(examples/workflow_api/basic-examples/bare-metal-complex-job)
add_subdirectory(examples/workflow_api/basic-examples/bare-metal-data-movement)
add_subdirectory(examples/workflow_api/basic-examples/cloud-bag-of-tasks)
add_subdirectory(examples/workflow_api/basic-examples/cloud-bag-of-tasks-energy)
add_subdirectory(examples/workflow_api/basic-examples/virtualized-cluster-bag-of-tasks)
add_subdirectory(examples/workflow_api/basic-examples/batch-bag-of-tasks)
add_subdirectory(examples/workflow_api/basic-examples/batch-pilot-job)
add_subdirectory(examples/workflow_api/real-workflow-example)
add_subdirectory(examples/workflow_api/condor-grid-example)
add_subdirectory(examples/workflow_api/basic-examples/io-pagecache)

add_subdirectory(examples/action_api/bare-metal-bag-of-actions EXCLUDE_FROM_ALL)
add_subdirectory(examples/action_api/batch-bag-of-actions EXCLUDE_FROM_ALL)
add_subdirectory(examples/action_api/cloud-bag-of-actions EXCLUDE_FROM_ALL)
add_subdirectory(examples/action_api/multi-action-multi-job EXCLUDE_FROM_ALL)
add_subdirectory(examples/action_api/job-action-failure EXCLUDE_FROM_ALL)
add_subdirectory(examples/action_api/super-custom-action EXCLUDE_FROM_ALL)
