//
// Created by Henri Casanova on 1/5/21.
//

#ifndef WRENCH_CONSERVATIVEBFBATCHSCHEDULERCORELEVEL_H
#define WRENCH_CONSERVATIVEBFBATCHSCHEDULERCORELEVEL_H


class CONSERVATIVEBFBatchSchedulerCoreLevel {

};


#endif //WRENCH_CONSERVATIVEBFBATCHSCHEDULERCORELEVEL_H
