name: clang-format

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        exclude: './doc'
        extensions: 'h,cpp'
        clangFormatVersion: 13
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
